name: lstn scan 

on: 
  pull_request:
    branches: ["*"]

permissions:
  contents: read
  pull-requests: write

jobs:
    lstn-cli-e2e:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repo
          uses: actions/checkout@v3
  
        - name: lstn scan
          uses: listendev/action@v0.2.2
          with:
            lstn_flags: "--ignore-deptypes=peer --ignore-packages=react"
      
